name: "Entra: Set PIM Settings"

on:
  #pull-request:
  #  types: [opened, synchronize, reopened]
  #  paths:
  #    - '.github/workflows/ps-set-pim-settings.yml'
  ## checkov:skip=CKV_GHA_7:Workflow_dispatch should not take any inputs.
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - production
          - staging
          - development
      execute:
        required: true
        type: boolean
        description: Execute Change
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  IS_AZURE_GOV: ${{ vars.IS_AZURE_GOV }}
  ExecuteChange: "${{ inputs.execute || 'false' }}"
  PIM_SETTINGS: "${{ vars.PIM_SETTINGS }}"  # Ensure this is set as a boolean in the repo variables

jobs:
  run-powershell-script:
    environment: ${{ inputs.environment || vars.MANAGEMENT_TENANT_NAME }}
    name: "PIM Settings Configuration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PIMSettings module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.124'  # Update to the latest version
          path: 'EZD.ECI.PIMSettings'
          sparse-checkout: 'powershell-modules/EZD.ECI.PIMSettings'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.124'  # Update to the latest version
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Authenticate and Configure PIM Settings
        shell: pwsh
        run: |
          # Install And Import Modules
          Install-Module -Name "Microsoft.Graph.Identity.Management" -Force
          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psd1 -Force

          Connect-EciGraph
          Import-Module .\EZD.ECI.PIMSettings\powershell-modules\EZD.ECI.PIMSettings\EZD.ECI.PIMSettings.psd1 -Force

          Write-Output "Configuring PIM Settings"
          # Set the PIM settings
          Set-PIMSettings -ExecuteChange $env:ExecuteChange
