name: Build and Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1) Compute lowercase owner from GITHUB_REPOSITORY (OWNER/REPO)
      - name: Set lowercase owner
        id: lcowner
        run: |
          owner=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')
          echo "owner_lower=$owner" >> $GITHUB_OUTPUT

      # 2) Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3) Build & push, using our lowercased owner
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.lcowner.outputs.owner_lower }}/arc-runner-image:latest
            ghcr.io/${{ steps.lcowner.outputs.owner_lower }}/arc-runner-image:${{ github.sha }}

      - name: Done
        run: echo "Published as ghcr.io/${{ steps.lcowner.outputs.owner_lower }}/arc-runner-image:latest"
