name: "Entra: Configure Entra ID Password Expiration Policies"

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Environment to deploy to
        options:
          - sumvita-gov
          - sumvita
          - kalvico
      execute:
        required: true
        type: boolean
        description: Execute change
        default: false
      password_policy:
        required: true
        type: choice
        description: Password policy setting
        options:
          - Expire
          - NeverExpire
      password_validity_period_in_days:
        required: false
        type: number
        description: Validity period in days (only required if 'Expire' is selected)

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_ENVIRONMENT: ${{ vars.TF_BACKEND_CONFIG_ENVIRONMENT }}
  ARM_SUBSCRIPTION_ID: ${{ vars.TFSTATE_AZURE_SUBSCRIPTION_ID }}
  IS_AZURE_GOV: ${{ vars.IS_AZURE_GOV }}
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

jobs:
  run-powershell-script:
    environment: ${{ inputs.environment }}
    name: "Organization-wide Password Expiration Policy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PasswordPolicy module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: 'Noah/PasswordPolicy'
          path: 'EZD.ECI.EntraUserPasswordExpiration'
          sparse-checkout: 'powershell-modules/EZD.ECI.PasswordPolicy'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Checkout common module
        uses: actions/checkout@v4
        with:
          repository: 'EasyDynamics/EntraID-800-53-Terraform-Modules'
          ref: '0.0.95'
          path: 'EZD.ECI.Common'
          sparse-checkout: 'powershell-modules/EZD.ECI.Common'
          ssh-key: ${{ secrets.MODULES_REPO_SSH_PRIVATE_KEY }}

      - name: Configure Entra ID Password Expiration Settings
        shell: pwsh
        run: |
          if ($env:IS_AZURE_GOV -eq "true") {
            az cloud set --name AzureUSGovernment
            $GRAPH_ENVIRONMENT = 'USGov'
          } else {
            $GRAPH_ENVIRONMENT = 'Global'
          }
          az login --service-principal -u $env:AZURE_CLIENT_ID -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant $env:AZURE_TENANT_ID
          $AccessToken = (az account get-access-token --resource-type ms-graph | ConvertFrom-Json).accessToken

          Write-Output "Connecting to MgGraph..."
          $SecureAccessToken = ConvertTo-SecureString -String $AccessToken -AsPlainText -Force
          Connect-MgGraph -AccessToken $SecureAccessToken -NoWelcome -Environment $GRAPH_ENVIRONMENT

          Write-Output "Installing Microsoft Graph Identity Directory Management Module"
          # Install Microsoft.Graph.Identity.DirectoryManagement module if not already installed
          if (-Not (Get-InstalledModule -Name "Microsoft.Graph.Identity.DirectoryManagement" -ErrorAction SilentlyContinue)) {
            Write-Output "Installing Microsoft.Graph.Identity.DirectoryManagement module..."
            Install-Module -Name "Microsoft.Graph.Identity.DirectoryManagement" -Scope CurrentUser -Force
          }

          # Verify that the required Microsoft Graph Identity Directory Management module is installed
          if (-Not (Get-InstalledModule -Name "Microsoft.Graph.Identity.DirectoryManagement" -ErrorAction SilentlyContinue)) {
            Write-Error "Microsoft.Graph.Identity.DirectoryManagement module is not installed. Please install it before running this workflow."
            exit 1
          }

          Write-Output "Importing Graph Module"
          # Import the Microsoft.Graph.Identity.DirectoryManagement module into the session
          Import-Module -Name "Microsoft.Graph.Identity.DirectoryManagement" -Force

          Write-Output "Importing Password Expiration Policy And Common Modules"
          # Import custom modules
          Import-Module .\EZD.ECI.Common\powershell-modules\EZD.ECI.Common\EZD.ECI.Common.psm1 -Force
          Import-Module .\EZD.ECI.EntraUserPasswordExpiration\powershell-modules\EZD.ECI.PasswordPolicy\EZD.ECI.EntraIdUserPasswordPolicyConfig.psm1 -Force

          Write-Output "Defining Variables"
          # Define variables
          $PasswordPolicy = "${{ github.event.inputs.password_policy }}"
          $ExecuteChange = [System.Convert]::ToBoolean("${{ github.event.inputs.execute }}")

          if ($PasswordPolicy -eq "Expire") {
            $PasswordValidityPeriodInDays = ${{ github.event.inputs.password_validity_period_in_days }}
            if (-not $PasswordValidityPeriodInDays) {
              Write-Error "PasswordValidityPeriodInDays must be specified when PasswordPolicy is 'Expire'."
              exit 1
            }
          } elseif ($PasswordPolicy -eq "NeverExpire") {
            $PasswordValidityPeriodInDays = 2147483647 # A large number to represent never expire
          } else {
            Write-Error "Invalid PasswordPolicy value."
            exit 1
          }

          Write-Output "Password Policy: $PasswordPolicy"
          Write-Output "Password Validity Period In Days: $PasswordValidityPeriodInDays"

          Write-Output "Configuring Password Expiration Settings"
          # Configure Entra ID password expiration settings
          Set-DomainPasswordPolicy -PasswordPolicy $PasswordPolicy -PasswordValidityPeriodInDays $PasswordValidityPeriodInDays -ExecuteChange:$ExecuteChange